 jenkins:
    image: mohamadassi173/jenkins_flutter
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/data/jenkins-flutter-android:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always